services:
  mysql:
    build:
      context: ../database
      dockerfile: ../database/Dockerfile
    container_name: nova-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - traefik-network

volumes:
  mysql-data:

networks:
  traefik-network:
    external: true
